apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: suimmapipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: suimmapipelinesjavascriptdocker 
    spec:
      containers:
        - name: suimmapipelinesjavascriptdocker 
          image: testacreus.azurecr.io/suimmapipelinesjavascriptdocker
          ports:
          - containerPort: 8080